// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tendermint/rpc/grpc/txstream.proto

package coregrpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type TxStreamRequest struct {
	Tx        []byte `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`
	Mode      string `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`
	RequestId string `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
}

func (m *TxStreamRequest) Reset()         { *m = TxStreamRequest{} }
func (m *TxStreamRequest) String() string { return proto.CompactTextString(m) }
func (*TxStreamRequest) ProtoMessage()    {}
func (*TxStreamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6cfd134105c442f, []int{0}
}
func (m *TxStreamRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TxStreamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TxStreamRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TxStreamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxStreamRequest.Merge(m, src)
}
func (m *TxStreamRequest) XXX_Size() int {
	return m.Size()
}
func (m *TxStreamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TxStreamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TxStreamRequest proto.InternalMessageInfo

func (m *TxStreamRequest) GetTx() []byte {
	if m != nil {
		return m.Tx
	}
	return nil
}

func (m *TxStreamRequest) GetMode() string {
	if m != nil {
		return m.Mode
	}
	return ""
}

func (m *TxStreamRequest) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

type TxStreamResponse struct {
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Mode      string `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`
	Code      uint32 `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	Log       string `protobuf:"bytes,4,opt,name=log,proto3" json:"log,omitempty"`
	Data      []byte `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	TxHash    string `protobuf:"bytes,6,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
}

func (m *TxStreamResponse) Reset()         { *m = TxStreamResponse{} }
func (m *TxStreamResponse) String() string { return proto.CompactTextString(m) }
func (*TxStreamResponse) ProtoMessage()    {}
func (*TxStreamResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6cfd134105c442f, []int{1}
}
func (m *TxStreamResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TxStreamResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TxStreamResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TxStreamResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxStreamResponse.Merge(m, src)
}
func (m *TxStreamResponse) XXX_Size() int {
	return m.Size()
}
func (m *TxStreamResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TxStreamResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TxStreamResponse proto.InternalMessageInfo

func (m *TxStreamResponse) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *TxStreamResponse) GetMode() string {
	if m != nil {
		return m.Mode
	}
	return ""
}

func (m *TxStreamResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *TxStreamResponse) GetLog() string {
	if m != nil {
		return m.Log
	}
	return ""
}

func (m *TxStreamResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *TxStreamResponse) GetTxHash() string {
	if m != nil {
		return m.TxHash
	}
	return ""
}

func init() {
	proto.RegisterType((*TxStreamRequest)(nil), "tendermint.rpc.grpc.TxStreamRequest")
	proto.RegisterType((*TxStreamResponse)(nil), "tendermint.rpc.grpc.TxStreamResponse")
}

func init() {
	proto.RegisterFile("tendermint/rpc/grpc/txstream.proto", fileDescriptor_b6cfd134105c442f)
}

var fileDescriptor_b6cfd134105c442f = []byte{
	// 313 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0x31, 0x4b, 0x03, 0x31,
	0x14, 0x80, 0x9b, 0xb6, 0x56, 0x1a, 0xd4, 0x96, 0x38, 0x18, 0x04, 0x43, 0x29, 0x0a, 0x9d, 0x52,
	0xd1, 0xd1, 0xad, 0x53, 0x5d, 0xaf, 0x9d, 0x5c, 0x4a, 0x2e, 0x89, 0xbd, 0x03, 0xaf, 0x39, 0x93,
	0x57, 0xc9, 0xcf, 0x70, 0xf4, 0x27, 0x39, 0x76, 0x74, 0x94, 0xf6, 0x8f, 0x48, 0x52, 0xe5, 0xe0,
	0x28, 0xb8, 0x1c, 0x1f, 0xef, 0x7d, 0xef, 0x5e, 0xde, 0x7b, 0x78, 0x08, 0x7a, 0xa5, 0xb4, 0x2d,
	0xf2, 0x15, 0x8c, 0x6d, 0x29, 0xc7, 0xcb, 0xf0, 0x01, 0xef, 0xc0, 0x6a, 0x51, 0xf0, 0xd2, 0x1a,
	0x30, 0xe4, 0xbc, 0x72, 0xb8, 0x2d, 0x25, 0x0f, 0xce, 0x70, 0x8e, 0x7b, 0x73, 0x3f, 0x8b, 0x5a,
	0xa2, 0x5f, 0xd7, 0xda, 0x01, 0x39, 0xc3, 0x4d, 0xf0, 0x14, 0x0d, 0xd0, 0xe8, 0x24, 0x69, 0x82,
	0x27, 0x04, 0xb7, 0x0b, 0xa3, 0x34, 0x6d, 0x0e, 0xd0, 0xa8, 0x9b, 0x44, 0x26, 0x57, 0x18, 0xdb,
	0xbd, 0xbe, 0xc8, 0x15, 0x6d, 0xc5, 0x4c, 0xf7, 0x37, 0xf2, 0xa8, 0x86, 0x1f, 0x08, 0xf7, 0xab,
	0xdf, 0xba, 0xd2, 0xac, 0x5c, 0xbd, 0x06, 0xd5, 0x6a, 0x0e, 0xb6, 0x21, 0xb8, 0x2d, 0x43, 0x2c,
	0x34, 0x38, 0x4d, 0x22, 0x93, 0x3e, 0x6e, 0xbd, 0x98, 0x25, 0x6d, 0x47, 0x2d, 0x60, 0xb0, 0x94,
	0x00, 0x41, 0x8f, 0xe2, 0x93, 0x23, 0x93, 0x0b, 0x7c, 0x0c, 0x7e, 0x91, 0x09, 0x97, 0xd1, 0x4e,
	0x34, 0x3b, 0xe0, 0xa7, 0xc2, 0x65, 0x77, 0xeb, 0x6a, 0xe0, 0x99, 0xb6, 0x6f, 0xb9, 0xd4, 0x24,
	0xc5, 0xbd, 0x89, 0x35, 0x42, 0x49, 0xe1, 0x60, 0x9f, 0x21, 0xd7, 0xfc, 0xc0, 0xb2, 0x78, 0x6d,
	0x53, 0x97, 0x37, 0xff, 0x58, 0xfb, 0xc1, 0x47, 0xe8, 0x16, 0x4d, 0xa6, 0x9f, 0x5b, 0x86, 0x36,
	0x5b, 0x86, 0xbe, 0xb7, 0x0c, 0xbd, 0xef, 0x58, 0x63, 0xb3, 0x63, 0x8d, 0xaf, 0x1d, 0x6b, 0x3c,
	0xf1, 0x65, 0x0e, 0xd9, 0x3a, 0xe5, 0xd2, 0x14, 0x63, 0x69, 0x0a, 0x0d, 0xe9, 0x33, 0x54, 0xf0,
	0x77, 0xcc, 0x07, 0x69, 0xac, 0x0e, 0x90, 0x76, 0xe2, 0x35, 0xef, 0x7f, 0x02, 0x00, 0x00, 0xff,
	0xff, 0x78, 0x59, 0x29, 0x5e, 0xf3, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TxStreamServiceClient is the client API for TxStreamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TxStreamServiceClient interface {
	// bidi-stream: клиент шлёт поток tx, сервер шлёт поток ответов
	BroadcastStream(ctx context.Context, opts ...grpc.CallOption) (TxStreamService_BroadcastStreamClient, error)
}

type txStreamServiceClient struct {
	cc *grpc.ClientConn
}

func NewTxStreamServiceClient(cc *grpc.ClientConn) TxStreamServiceClient {
	return &txStreamServiceClient{cc}
}

func (c *txStreamServiceClient) BroadcastStream(ctx context.Context, opts ...grpc.CallOption) (TxStreamService_BroadcastStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_TxStreamService_serviceDesc.Streams[0], "/tendermint.rpc.grpc.TxStreamService/BroadcastStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &txStreamServiceBroadcastStreamClient{stream}
	return x, nil
}

type TxStreamService_BroadcastStreamClient interface {
	Send(*TxStreamRequest) error
	Recv() (*TxStreamResponse, error)
	grpc.ClientStream
}

type txStreamServiceBroadcastStreamClient struct {
	grpc.ClientStream
}

func (x *txStreamServiceBroadcastStreamClient) Send(m *TxStreamRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *txStreamServiceBroadcastStreamClient) Recv() (*TxStreamResponse, error) {
	m := new(TxStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TxStreamServiceServer is the server API for TxStreamService service.
type TxStreamServiceServer interface {
	// bidi-stream: клиент шлёт поток tx, сервер шлёт поток ответов
	BroadcastStream(TxStreamService_BroadcastStreamServer) error
}

// UnimplementedTxStreamServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTxStreamServiceServer struct {
}

func (*UnimplementedTxStreamServiceServer) BroadcastStream(srv TxStreamService_BroadcastStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method BroadcastStream not implemented")
}

func RegisterTxStreamServiceServer(s *grpc.Server, srv TxStreamServiceServer) {
	s.RegisterService(&_TxStreamService_serviceDesc, srv)
}

func _TxStreamService_BroadcastStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TxStreamServiceServer).BroadcastStream(&txStreamServiceBroadcastStreamServer{stream})
}

type TxStreamService_BroadcastStreamServer interface {
	Send(*TxStreamResponse) error
	Recv() (*TxStreamRequest, error)
	grpc.ServerStream
}

type txStreamServiceBroadcastStreamServer struct {
	grpc.ServerStream
}

func (x *txStreamServiceBroadcastStreamServer) Send(m *TxStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *txStreamServiceBroadcastStreamServer) Recv() (*TxStreamRequest, error) {
	m := new(TxStreamRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _TxStreamService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tendermint.rpc.grpc.TxStreamService",
	HandlerType: (*TxStreamServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "BroadcastStream",
			Handler:       _TxStreamService_BroadcastStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "tendermint/rpc/grpc/txstream.proto",
}

func (m *TxStreamRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TxStreamRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TxStreamRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RequestId) > 0 {
		i -= len(m.RequestId)
		copy(dAtA[i:], m.RequestId)
		i = encodeVarintTxstream(dAtA, i, uint64(len(m.RequestId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Mode) > 0 {
		i -= len(m.Mode)
		copy(dAtA[i:], m.Mode)
		i = encodeVarintTxstream(dAtA, i, uint64(len(m.Mode)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Tx) > 0 {
		i -= len(m.Tx)
		copy(dAtA[i:], m.Tx)
		i = encodeVarintTxstream(dAtA, i, uint64(len(m.Tx)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *TxStreamResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TxStreamResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TxStreamResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TxHash) > 0 {
		i -= len(m.TxHash)
		copy(dAtA[i:], m.TxHash)
		i = encodeVarintTxstream(dAtA, i, uint64(len(m.TxHash)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Data) > 0 {
		i -= len(m.Data)
		copy(dAtA[i:], m.Data)
		i = encodeVarintTxstream(dAtA, i, uint64(len(m.Data)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Log) > 0 {
		i -= len(m.Log)
		copy(dAtA[i:], m.Log)
		i = encodeVarintTxstream(dAtA, i, uint64(len(m.Log)))
		i--
		dAtA[i] = 0x22
	}
	if m.Code != 0 {
		i = encodeVarintTxstream(dAtA, i, uint64(m.Code))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Mode) > 0 {
		i -= len(m.Mode)
		copy(dAtA[i:], m.Mode)
		i = encodeVarintTxstream(dAtA, i, uint64(len(m.Mode)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.RequestId) > 0 {
		i -= len(m.RequestId)
		copy(dAtA[i:], m.RequestId)
		i = encodeVarintTxstream(dAtA, i, uint64(len(m.RequestId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTxstream(dAtA []byte, offset int, v uint64) int {
	offset -= sovTxstream(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *TxStreamRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Tx)
	if l > 0 {
		n += 1 + l + sovTxstream(uint64(l))
	}
	l = len(m.Mode)
	if l > 0 {
		n += 1 + l + sovTxstream(uint64(l))
	}
	l = len(m.RequestId)
	if l > 0 {
		n += 1 + l + sovTxstream(uint64(l))
	}
	return n
}

func (m *TxStreamResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.RequestId)
	if l > 0 {
		n += 1 + l + sovTxstream(uint64(l))
	}
	l = len(m.Mode)
	if l > 0 {
		n += 1 + l + sovTxstream(uint64(l))
	}
	if m.Code != 0 {
		n += 1 + sovTxstream(uint64(m.Code))
	}
	l = len(m.Log)
	if l > 0 {
		n += 1 + l + sovTxstream(uint64(l))
	}
	l = len(m.Data)
	if l > 0 {
		n += 1 + l + sovTxstream(uint64(l))
	}
	l = len(m.TxHash)
	if l > 0 {
		n += 1 + l + sovTxstream(uint64(l))
	}
	return n
}

func sovTxstream(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTxstream(x uint64) (n int) {
	return sovTxstream(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *TxStreamRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTxstream
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TxStreamRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TxStreamRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tx", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTxstream
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTxstream
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTxstream
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tx = append(m.Tx[:0], dAtA[iNdEx:postIndex]...)
			if m.Tx == nil {
				m.Tx = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mode", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTxstream
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTxstream
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTxstream
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Mode = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTxstream
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTxstream
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTxstream
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RequestId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTxstream(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTxstream
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TxStreamResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTxstream
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TxStreamResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TxStreamResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTxstream
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTxstream
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTxstream
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RequestId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mode", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTxstream
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTxstream
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTxstream
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Mode = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Code", wireType)
			}
			m.Code = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTxstream
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Code |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Log", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTxstream
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTxstream
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTxstream
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Log = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTxstream
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTxstream
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTxstream
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = append(m.Data[:0], dAtA[iNdEx:postIndex]...)
			if m.Data == nil {
				m.Data = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTxstream
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTxstream
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTxstream
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TxHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTxstream(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTxstream
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTxstream(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTxstream
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTxstream
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTxstream
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTxstream
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTxstream
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTxstream
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTxstream        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTxstream          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTxstream = fmt.Errorf("proto: unexpected end of group")
)
